=head1 NAME

Dongry::Type::DateTime - Dongry data types for date and time as DateTime object

=head1 DESCRIPTION

The C<Dongry::Type::DateTime> module defines data types for handing
date and time in Dongry.  They represents date and time in Perl
L<DateTime> object.

=head1 DATA TYPES

=over 4

=item timestamp_as_DateTime

Perl -> SQL: The input must be a L<DateTime> object or the C<undef>
value.  If the input is a L<DateTime> object, it is converted into the
canonical representation of the C<TIMESTAMP> data type in MySQL
version 5, in the UTC time zone.  The C<undef> value is converted into
C<0000-00-00 00:00:00>.

SQL -> Perl: The input must be a date-time in the canonical
representation of the C<TIMESTAMP> data type in MySQL version 5, in
the UTC time zone.  If the input is C<0000-00-00 00:00:00>, the
C<undef> value is returned.  Otherwise, the L<DateTime> object for the
date-time is returned.

=item timestamp_jst_as_DateTime

Perl -> SQL: The input must be a L<DateTime> object or the C<undef>
value.  If the input is a L<DateTime> object, it is converted into the
canonical representation of the C<TIMESTAMP> data type in MySQL
version 5, in the Japanese Central Standard Time (+09:00).  The
C<undef> value is converted into C<0000-00-00 00:00:00>.

SQL -> Perl: The input must be a date-time in the canonical
representation of the C<TIMESTAMP> data type in MySQL version 5, in
the Japanese Central Standard Time (+09:00).  If the input is
C<0000-00-00 00:00:00>, the C<undef> value is returned.  Otherwise,
the L<DateTime> object for the date-time is returned.

=item date_as_DateTime

Perl -> SQL: The input must be a L<DateTime> object or the C<undef>
value.  If the input is a L<DateTime> object, it is converted into the
canonical representation of the C<DATE> data type in MySQL version 5,
in the UTC time zone.  The time (hour, minute, and second) component
is ignored.  The C<undef> value is converted into C<0000-00-00>.

SQL -> Perl: The input must be a date in the canonical representation
of the C<DATE> data type in MySQL version 5.  If the input is
C<0000-00-00>, the C<undef> value is returned.  Otherwise, the
L<DateTime> object for the date, with the time component set to
00:00:00 UTC, is returned.

=back

=head1 SEE ALSO

L<Dongry::Type>.

L<Dongry::Type::Time> - handle date and time as time_t.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2011 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
