=head1 NAME

Dongry::Type::JSONPS - Dongry data types for JSON, using |JSON::PS|

=head1 DESCRIPTION

The C<Dongry::Type::JSONPS> module defines data types for handing
JSON-encoded data structure as column value in Dongry.  The module
uses L<JSON::PS>.

=head1 DATA TYPE

The following data type is defined by this module:

=over 4

=item json

Perl -> SQL: The input must be a scalar value.  If it is not the
C<undef> value, it is converted into JSON.

SQL -> Perl: The input must be a byte string or the C<undef> value.
If it is not the C<undef> value, it is parsed as JSON.

The Perl C<undef> value represents the C<NULL> value of SQL.

=back

=head1 DEPENDENCY

The module requires L<JSON::PS>.  The latest version of the module is
available from <https://github.com/wakaba/perl-json-ps>.

=head1 SEE ALSO

L<Dongry::Type>.

L<JSON::PS>.

L<Dongry::Type::JSON>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2011-2015 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
