=head1 NAME

Dongry::Type::Time - Dongry data types for date and time in time_t format

=head1 DESCRIPTION

The C<Dongry::Type::Time> module defines data types for handing date
and time in Dongry.  They represents date and time in time_t (or Unix
epoch time) format in Perl.

=head1 DATA TYPES

=over 4

=item timestamp

SQL format: Canonical representation of L<TIMESTAMP> in MySQL 5, in
the UTC time zone.

Perl value: Integer of seconds from the Unix epoch (i.e. the Unix
epoch time or time_t format).

SQL C<0000-00-00 00:00:00> value is mapped to Perl C<undef> value.

=item timestamp_jst

SQL format: Canonical representation of L<TIMESTAMP> in MySQL 5, in
the Japanese Central Standard Time (+09:00).

Perl value: Integer of seconds from the Unix epoch (i.e. the Unix
epoch time or time_t format).

SQL C<0000-00-00 00:00:00> value is mapped to Perl C<undef> value.

=item date

SQL format: Canonical representation of L<DATE> in MySQL 5.

Perl value: Integer of seconds from the Unix epoch (i.e. the Unix
epoch time or time_t format) of time 00:00:00 in UTC.

SQL C<0000-00-00> value is mapped to Perl C<undef> value.

=back

=head1 SEE ALSO

L<Dongry::Type>.

L<Dongry::Type::DateTime> - handle date and time as L<DateTime>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2011 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
