
CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY (name),
  KEY (created_on)
) DEFAULT CHARSET=BINARY;
